deckData.push({
	name: "Asset",
	subtitle: " (Non-Unique)",
	cssClass: "asset",
	canRearrangeTop: true,
	cardsByExpansions: [
		{
			expansionID: 0,
			cards: [
				{
					id: 1,
					name: ".18 Derringer",
					traits: ["Trinket", "Weapon"],
					cost: 1,
				},
				{
					id: 2,
					name: ".38 Revolver",
					traits: ["Item", "Weapon"],
					cost: 1,
				},
				{
					id: 3,
					name: ".45 Automatic",
					traits: ["Item", "Weapon"],
					cost: 2,
				},
				{
					id: 4,
					name: "Agency Quarantine",
					traits: ["Service"],
					cost: 4,
				},
				{
					id: 5,
					name: "Arcane Manuscripts",
					traits: ["Item", "Tome"],
					cost: 1,
				},
				{
					id: 6,
					name: "Arcane Scholar",
					traits: ["Ally"],
					cost: 2,
				},
				{
					id: 7,
					name: "Arcane Tome",
					traits: ["Item", "Tome"],
					cost: 3,
				},
				{
					id: 8,
					name: "Axe",
					traits: ["Item", "Weapon"],
					cost: 2,
				},
				{
					id: 9,
					name: "Bandages",
					traits: ["Item"],
					cost: 1,
				},
				{
					id: 10,
					name: "Bull Whip",
					traits: ["Item", "Weapon"],
					cost: 1,
				},
				{
					id: 11,
					name: "Carbine Rifle",
					traits: ["Item", "Weapon"],
					cost: 3,
				},
				{
					id: 12,
					name: "Cat Burglar",
					traits: ["Ally"],
					cost: 1,
				},
				{
					id: 13,
					name: "Charter Flight",
					traits: ["Service"],
					cost: 1,
				},
				{
					id: 14,
					name: "Delivery Service",
					traits: ["Service", "Teamwork"],
					cost: 1,
				},
				{
					id: 15,
					name: "Double-barreled Shotgun",
					traits: ["Item", "Weapon"],
					cost: 4,
				},
				{
					id: 16,
					name: "Dynamite",
					traits: ["Item", "Weapon"],
					cost: 3,
				},
				{
					id: 17,
					name: "Fine Clothes",
					traits: ["Item"],
					cost: 2,
				},
				{
					id: 18,
					name: "Fishing Net",
					traits: ["Item"],
					cost: 2,
				},
				{
					id: 19,
					name: "Hired Muscle",
					traits: ["Ally"],
					cost: 2,
				},
				{
					id: 20,
					name: "Holy Cross",
					traits: ["Item"],
					cost: 2,
				},
				{
					id: 21,
					name: "Holy Water",
					traits: ["Item", "Magical"],
					cost: 2,
				},
				{
					id: 22,
					name: "Kerosene",
					traits: ["Item"],
					cost: 1,
				},
				{
					id: 23,
					name: "King James Bible",
					traits: ["Item", "Tome"],
					cost: 2,
				},
				{
					id: 24,
					name: "Lodge Researcher",
					traits: ["Ally"],
					cost: 3,
				},
				{
					id: 25,
					name: "Lucky Cigarette Case",
					traits: ["Trinket"],
					cost: 2,
				},
				{
					id: 26,
					name: "Lucky Rabbit's Foot",
					traits: ["Trinket"],
					cost: 1,
				},
				{
					id: 27,
					name: "Personal Assistant",
					traits: ["Ally"],
					cost: 2,
				},
				{
					id: 28,
					name: "Pocket Watch",
					traits: ["Trinket"],
					cost: 1,
				},
				{
					id: 29,
					name: "Private Care",
					traits: ["Service"],
					cost: 2,
				},
				{
					id: 30,
					name: "Private Investigator",
					traits: ["Ally"],
					cost: 2,
				},
				{
					id: 31,
					name: "Protective Amulet",
					traits: ["Item"],
					cost: 1,
				},
				{
					id: 32,
					name: "Puzzle Box",
					traits: ["Trinket"],
					cost: 3,
				},
				{
					id: 33,
					name: "Sanctuary",
					traits: ["Service"],
					cost: 2,
				},
				{
					id: 34,
					name: "Silver Twilight Ritual",
					traits: ["Service"],
					cost: 3,
				},
				{
					id: 35,
					name: "Spirit Dagger",
					traits: ["Item", "Weapon", "Magical"],
					cost: 2,
				},
				{
					id: 36,
					name: "Urban Guide",
					traits: ["Ally"],
					cost: 4,
				},
				{
					id: 37,
					name: "Vatican Missionary",
					traits: ["Ally"],
					cost: 2,
				},
				{
					id: 38,
					name: "Whiskey",
					traits: ["Item"],
					cost: 1,
				},
				{
					id: 39,
					name: "Wireless Report",
					traits: ["Service", "Teamwork"],
					cost: 1,
				},
				{
					id: 40,
					name: "Witch Doctor",
					traits: ["Ally"],
					cost: 3,
				},
			],
		},
		{
			expansionID: 1,
			cards: [
				{
					id: 41,
					name: ".45 Colt Revolver",
					traits: ["Item", "Weapon"],
					cost: 1,
				},
				{
					id: 42,
					name: "Appeal to the Council",
					traits: ["Service"],
					cost: 1,
				},
				{
					id: 43,
					name: "Bodyguard",
					traits: ["Ally"],
					cost: 2,
				},
				{
					id: 44,
					name: "Conspiracy Theorist",
					traits: ["Ally"],
					cost: 3,
				},
				{
					id: 45,
					name: "Elder Sign",
					traits: ["Trinket", "Magical"],
					cost: 2,
				},
				{
					id: 46,
					name: "Enchanted Blade",
					traits: ["Item", "Magical", "Weapon"],
					cost: 3,
				},
				{
					id: 47,
					name: "Fresh Fruit",
					traits: ["Item"],
					cost: 1,
				},
				{
					id: 48,
					name: "Intelligence Report",
					traits: ["Service"],
					cost: 3,
				},
				{
					id: 49,
					name: "Lantern",
					traits: ["Item"],
					cost: 1,
				},
				{
					id: 50,
					name: "Lucky Ring",
					traits: ["Trinket"],
					cost: 3,
				},
				{
					id: 51,
					name: "Mystic Bounty Hunter",
					traits: ["Ally"],
					cost: 2,
				},
				{
					id: 52,
					name: "Police Assistance",
					traits: ["Service"],
					cost: 1,
				},
				{
					id: 53,
					name: "Police Ledger",
					traits: ["Item"],
					cost: 1,
				},
				{
					id: 54,
					name: "Research Student",
					traits: ["Ally"],
					cost: 1,
				},
				{
					id: 55,
					name: "Syndicate Agent",
					traits: ["Ally"],
					cost: 2,
				},
				{
					id: 56,
					name: "Tear Gas",
					traits: ["Item", "Weapon"],
					cost: 1,
				},
			],
		},
		{
			expansionID: 2,
			cards: [
				{
					id: 57,
					name: "Astronomy Guidebook",
					traits: ["Item", "Tome"],
					cost: 2,
				},
				{
					id: 58,
					name: "Blunderbuss",
					traits: ["Item", "Weapon"],
					cost: 2,
				},
				{
					id: 59,
					name: "Courier Needed!",
					traits: ["Service"],
					cost: 1,
				},
				{
					id: 60,
					name: "Cultist's Journal",
					traits: ["Item", "Tome", "Magical"],
					cost: 3,
				},
				{
					id: 61,
					name: "Gambler's Dice",
					traits: ["Trinket"],
					cost: 3,
				},
				{
					id: 62,
					name: "Genealogy Research",
					traits: ["Task"],
					cost: 1,
				},
				{
					id: 63,
					name: "Investment",
					traits: ["Task"],
					cost: 1,
				},
				{
					id: 64,
					name: "Map of the Ley Lines",
					traits: ["Item", "Tome"],
					cost: 4,
				},
				{
					id: 65,
					name: "Mineralogy Research",
					traits: ["Task"],
					cost: 1,
				},
				{
					id: 66,
					name: "Monster Hunter",
					traits: ["Ally"],
					cost: 3,
				},
				{
					id: 67,
					name: "Newspaper Report",
					traits: ["Task"],
					cost: 1,
				},
				{
					id: 68,
					name: "Patrolling the Streets",
					traits: ["Task"],
					cost: 1,
				},
				{
					id: 69,
					name: "Profane Tome",
					traits: ["Item", "Tome"],
					cost: 1,
				},
				{
					id: 70,
					name: "Search the Archives",
					traits: ["Service"],
					cost: 2,
				},
				{
					id: 71,
					name: "Secret Page",
					traits: ["Item", "Tome"],
					cost: 2,
				},
				{
					id: 72,
					name: "Tome of Horrors",
					traits: ["Item", "Tome"],
					cost: 3,
				},
			],
		},
		{
			expansionID: 3,
			cards: [
				{
					id: 73,
					name: "Agent of Secrets",
					traits: ["Ally"],
					cost: 4,
				},
				{
					id: 74,
					name: "Arcane Blade",
					traits: ["Item", "Magical", "Weapon"],
					cost: 3,
				},
				{
					id: 75,
					name: "Consecration",
					traits: ["Service"],
					cost: 2,
				},
				{
					id: 76,
					name: "Expedition Guide",
					traits: ["Ally"],
					cost: 2,
				},
				{
					id: 77,
					name: "Expedition Map",
					traits: ["Trinket", "Tome"],
					cost: 1,
				},
				{
					id: 78,
					name: "Gruesome Talisman",
					traits: ["Trinket"],
					cost: 1,
				},
				{
					id: 79,
					name: "Handcuffs",
					traits: ["Item"],
					cost: 2,
				},
				{
					id: 80,
					name: "Holy Spear",
					traits: ["Item", "Magical", "Relic", "Weapon"],
					cost: 3,
				},
				{
					id: 81,
					name: "Lavish Feast",
					traits: ["Service"],
					cost: 1,
				},
				{
					id: 82,
					name: "Medical Journal",
					traits: ["Item", "Tome"],
					cost: 2,
				},
				{
					id: 83,
					name: "Museum Curator",
					traits: ["Ally"],
					cost: 3,
				},
				{
					id: 84,
					name: "Mysterious Tome",
					traits: ["Item", "Tome"],
					cost: 2,
				},
				{
					id: 85,
					name: "Opus Arcana",
					traits: ["Item", "Tome"],
					cost: 2,
				},
				{
					id: 86,
					name: "Ritual Dagger",
					traits: ["Item", "Magical", "Weapon"],
					cost: 1,
				},
				{
					id: 87,
					name: "Specialized Training",
					traits: ["Task"],
					cost: 1,
				},
				{
					id: 88,
					name: "Tome of Secrets",
					traits: ["Item", "Tome"],
					cost: 3,
				},
			],
		},
		{
			expansionID: 4,
			cards: [
				{
					id: 89,
					name: ".32 Colt Pocket",
					traits: ["Item", "Weapon"],
					cost: 2,
				},
				{
					id: 90,
					name: "Ancient Tome",
					traits: ["Item", "Relic", "Tome"],
					cost: 2,
				},
				{
					id: 91,
					name: "Ankh",
					traits: ["Item", "Relic"],
					cost: 3,
				},
				{
					id: 92,
					name: "Arcane Scroll",
					traits: ["Trinket", "Tome"],
					cost: 1,
				},
				{
					id: 93,
					name: "Book of Spells",
					traits: ["Item", "Tome"],
					cost: 3,
				},
				{
					id: 94,
					name: "Curiosity Shoppe",
					traits: ["Service"],
					cost: 4,
				},
				{
					id: 95,
					name: "Enchanted Dagger",
					traits: ["Item", "Magical", "Weapon"],
					cost: 1,
				},
				{
					id: 96,
					name: "Lucky Talisman",
					traits: ["Trinket", "Relic"],
					cost: 3,
				},
				{
					id: 97,
					name: "Magick Shoppe",
					traits: ["Service"],
					cost: 2,
				},
				{
					id: 98,
					name: "Magnifying Glass",
					traits: ["Trinket"],
					cost: 1,
				},
				{
					id: 99,
					name: "Psychoanalyst",
					traits: ["Ally"],
					cost: 2,
				},
				{
					id: 100,
					name: "Ritual Candles",
					traits: ["Trinket"],
					cost: 1,
				},
				{
					id: 101,
					name: "Scribe's Journal",
					traits: ["Item", "Tome"],
					cost: 1,
				},
				{
					id: 102,
					name: "Sledgehammer",
					traits: ["Item"],
					cost: 2,
				},
				{
					id: 103,
					name: "Treasure Hunter",
					traits: ["Ally"],
					cost: 4,
				},
				{
					id: 104,
					name: "Ward Evil",
					traits: ["Service"],
					cost: 2,
				},
			],
		},
		{
			expansionID: 5,
			cards: [
				{
					id: 105,
					name: ".25 Automatic",
					traits: ["Item", "Weapon"],
					cost: 1,
				},
				{
					id: 106,
					name: "Arcane Assistant",
					traits: ["Ally"],
					cost: 1,
				},
				{
					id: 107,
					name: "Assassination",
					traits: ["Service"],
					cost: 2,
				},
				{
					id: 108,
					name: "Chief Inspector",
					traits: ["Ally"],
					cost: 2,
				},
				{
					id: 109,
					name: "Enchanted Cane",
					traits: ["Item", "Magical", "Weapon"],
					cost: 2,
				},
				{
					id: 110,
					name: "Esteemed Author",
					traits: ["Ally"],
					cost: 3,
				},
				{
					id: 111,
					name: "Fine Jewelry",
					traits: ["Trinket"],
					cost: 1,
				},
				{
					id: 112,
					name: "Flamethrower",
					traits: ["Item", "Weapon"],
					cost: 4,
				},
				{
					id: 113,
					name: "Lodge Disciple",
					traits: ["Ally"],
					cost: 4,
				},
				{
					id: 114,
					name: "Lodge Physician",
					traits: ["Ally"],
					cost: 3,
				},
				{
					id: 115,
					name: "Occult Text",
					traits: ["Item", "Tome"],
					cost: 2,
				},
				{
					id: 116,
					name: "Rumor Mill",
					traits: ["Service"],
					cost: 1,
				},
				{
					id: 117,
					name: "Security Squad",
					traits: ["Ally"],
					cost: 2,
				},
				{
					id: 118,
					name: "Specialist",
					traits: ["Ally"],
					cost: 3,
				},
				{
					id: 119,
					name: "Three-card Monte",
					traits: ["Service"],
					cost: 1,
				},
				{
					id: 120,
					name: "Tommy Gun",
					traits: ["Item", "Weapon"],
					cost: 3,
				},
			],
		},
		{
			expansionID: 6,
			cards: [
				{
					id: 121,
					name: "Alchemical Concoction",
					traits: ["Item", "Magical"],
					cost: 1,
				},
				{
					id: 122,
					name: "Arcanist",
					traits: ["Ally"],
					cost: 3,
				},
				{
					id: 123,
					name: "Camera",
					traits: ["Item"],
					cost: 2,
				},
				{
					id: 124,
					name: "Divination",
					traits: ["Service"],
					cost: 1,
				},
				{
					id: 125,
					name: "Dream Box",
					traits: ["Trinket", "Magical"],
					cost: 2,
				},
				{
					id: 126,
					name: "Dream Diary",
					traits: ["Item", "Tome"],
					cost: 1,
				},
				{
					id: 127,
					name: "Enchanted Bow",
					traits: ["Item", "Magical", "Weapon"],
					cost: 3,
				},
				{
					id: 128,
					name: "Forbidden Text",
					traits: ["Item", "Tome"],
					cost: 2,
				},
				{
					id: 129,
					name: "Hitman",
					traits: ["Ally"],
					cost: 3,
				},
				{
					id: 130,
					name: "Night Classes",
					traits: ["Service"],
					cost: 2,
				},
				{
					id: 131,
					name: "Occult Grimoire",
					traits: ["Item", "Tome"],
					cost: 3,
				},
				{
					id: 132,
					name: "Otherworld Codex",
					traits: ["Item", "Tome"],
					cost: 2,
				},
				{
					id: 133,
					name: "Police Raid",
					traits: ["Service"],
					cost: 3,
				},
				{
					id: 134,
					name: "Seek the Truth",
					traits: ["Task"],
					cost: 1,
				},
				{
					id: 135,
					name: "Skeleton Keys",
					traits: ["Trinket"],
					cost: 1,
				},
				{
					id: 136,
					name: "Willful Aristocrat",
					traits: ["Ally"],
					cost: 4,
				},
			],
		},
		{
			expansionID: 7,
			cards: [
				{
					id: 137,
					name: "Agency Stakeout",
					traits: ["Service"],
					cost: 3,
				},
				{
					id: 138,
					name: "Arcane Sutra",
					traits: ["Item", "Tome"],
					cost: 3,
				},
				{
					id: 139,
					name: "Forbidden Secrets",
					traits: ["Item", "Tome"],
					cost: 2,
				},
				{
					id: 140,
					name: "Gatling Gun",
					traits: ["Item", "Weapon"],
					cost: 4,
				},
				{
					id: 141,
					name: "Grisly Totem",
					traits: ["Trinket", "Magical"],
					cost: 3,
				},
				{
					id: 142,
					name: "Lodge Hunter",
					traits: ["Ally"],
					cost: 4,
				},
				{
					id: 143,
					name: "Mauser C96",
					traits: ["Item", "Weapon"],
					cost: 2,
				},
				{
					id: 144,
					name: "Mission Briefing",
					traits: ["Service"],
					cost: 1,
				},
				{
					id: 145,
					name: "Mystic Scroll",
					traits: ["Item", "Tome"],
					cost: 1,
				},
				{
					id: 146,
					name: "News Report",
					traits: ["Service"],
					cost: 1,
				},
				{
					id: 147,
					name: "Occult Scripture",
					traits: ["Item", "Tome"],
					cost: 3,
				},
				{
					id: 148,
					name: "Painkillers",
					traits: ["Trinket"],
					cost: 1,
				},
				{
					id: 149,
					name: "Private Flight",
					traits: ["Service"],
					cost: 2,
				},
				{
					id: 150,
					name: "Silver Twilight Host",
					traits: ["Service"],
					cost: 3,
				},
				{
					id: 151,
					name: "Training Regimen",
					traits: ["Service"],
					cost: 2,
				},
				{
					id: 152,
					name: "Winchester Rifle",
					traits: ["Item", "Weapon"],
					cost: 2,
				},
			],
		},
		{
			expansionID: 8,
			cards: [
				{
					id: 153,
					name: "Ancient Manuscript",
					traits: ["Trinket", "Relic", "Tome"],
					cost: 3,
				},
				{
					id: 154,
					name: "Astute Researcher",
					traits: ["Ally"],
					cost: 2,
				},
				{
					id: 155,
					name: "Blessed Blade",
					traits: ["Item", "Magical", "Relic", "Weapon"],
					cost: 3,
				},
				{
					id: 156,
					name: "Chainsaw",
					traits: ["Item"],
					cost: 3,
				},
				{
					id: 157,
					name: "Enchanted Jewelry",
					traits: ["Item", "Magical", "Relic"],
					cost: 3,
				},
				{
					id: 158,
					name: "Expert's Blade",
					traits: ["Item", "Magical", "Relic", "Weapon"],
					cost: 2,
				},
				{
					id: 159,
					name: "Grim Lexicon",
					traits: ["Item", "Tome"],
					cost: 2,
				},
				{
					id: 160,
					name: "Grotesque Compendium",
					traits: ["Item", "Tome"],
					cost: 4,
				},
				{
					id: 161,
					name: "Museum Director",
					traits: ["Ally"],
					cost: 4,
				},
				{
					id: 162,
					name: "Mystic Tome",
					traits: ["Item", "Tome"],
					cost: 3,
				},
				{
					id: 163,
					name: "Occult Tablet",
					traits: ["Item", "Relic", "Tome"],
					cost: 3,
				},
				{
					id: 164,
					name: "Protective Totem",
					traits: ["Item", "Magical", "Relic"],
					cost: 1,
				},
				{
					id: 165,
					name: "Scroll of Secrets",
					traits: ["Item", "Tome"],
					cost: 2,
				},
				{
					id: 166,
					name: "Timeworn Brand",
					traits: ["Item", "Magical", "Relic", "Weapon"],
					cost: 1,
				},
				{
					id: 167,
					name: "Treasured Memento",
					traits: ["Trinket"],
					cost: 1,
				},
				{
					id: 168,
					name: "Vampiric Talisman",
					traits: ["Item", "Magical", "Relic"],
					cost: 2,
				},
			],
		},
	],
});
