const ancientOneData = [
	{
		expansionID: 0,
		cards: [
			{
				id: 1,
				name: "Azathoth",
				mythosComposition: [
					{ stage: 1, color: "green", count: 1 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 1 },
					{ stage: 2, color: "green", count: 2 },
					{ stage: 2, color: "yellow", count: 3 },
					{ stage: 2, color: "blue", count: 1 },
					{ stage: 3, color: "green", count: 2 },
					{ stage: 3, color: "yellow", count: 4 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
			{
				id: 2,
				name: "Cthulhu",
				mythosComposition: [
					{ stage: 1, color: "green", count: 0 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 2 },
					{ stage: 2, color: "green", count: 1 },
					{ stage: 2, color: "yellow", count: 3 },
					{ stage: 2, color: "blue", count: 0 },
					{ stage: 3, color: "green", count: 3 },
					{ stage: 3, color: "yellow", count: 4 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
			{
				id: 3,
				name: "Shub-Niggurath",
				mythosComposition: [
					{ stage: 1, color: "green", count: 1 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 1 },
					{ stage: 2, color: "green", count: 3 },
					{ stage: 2, color: "yellow", count: 2 },
					{ stage: 2, color: "blue", count: 1 },
					{ stage: 3, color: "green", count: 2 },
					{ stage: 3, color: "yellow", count: 4 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
			{
				id: 4,
				name: "Yog-Sothoth",
				mythosComposition: [
					{ stage: 1, color: "green", count: 0 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 1 },
					{ stage: 2, color: "green", count: 2 },
					{ stage: 2, color: "yellow", count: 3 },
					{ stage: 2, color: "blue", count: 1 },
					{ stage: 3, color: "green", count: 3 },
					{ stage: 3, color: "yellow", count: 4 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
		],
	},
	{
		expansionID: 1,
		cards: [
			{
				id: 5,
				name: "Yig",
				mythosComposition: [
					{ stage: 1, color: "green", count: 1 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 1 },
					{ stage: 2, color: "green", count: 2 },
					{ stage: 2, color: "yellow", count: 3 },
					{ stage: 2, color: "blue", count: 1 },
					{ stage: 3, color: "green", count: 2 },
					{ stage: 3, color: "yellow", count: 4 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
		],
	},
	{
		expansionID: 2,
		cards: [
			{
				id: 6,
				name: "Rise of the Elder Things",
				mythosComposition: [
					{ stage: 1, color: "green", count: 2 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 1 },
					{ stage: 2, color: "green", count: 3 },
					{ stage: 2, color: "yellow", count: 3 },
					{ stage: 2, color: "blue", count: 1 },
					{ stage: 3, color: "green", count: 4 },
					{ stage: 3, color: "yellow", count: 4 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
			{
				id: 7,
				name: "Ithaqua",
				mythosComposition: [
					{ stage: 1, color: "green", count: 0 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 2 },
					{ stage: 2, color: "green", count: 4 },
					{ stage: 2, color: "yellow", count: 2 },
					{ stage: 2, color: "blue", count: 0 },
					{ stage: 3, color: "green", count: 2 },
					{ stage: 3, color: "yellow", count: 4 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
		],
	},
	{
		expansionID: 3,
		cards: [
			{
				id: 8,
				name: "Syzygy",
				mythosComposition: [
					{ stage: 1, color: "green", count: 0 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 2 },
					{ stage: 2, color: "green", count: 3 },
					{ stage: 2, color: "yellow", count: 3 },
					{ stage: 2, color: "blue", count: 0 },
					{ stage: 3, color: "green", count: 3 },
					{ stage: 3, color: "yellow", count: 5 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
		],
	},
	{
		expansionID: 4,
		cards: [
			{
				id: 9,
				name: "Abhoth",
				mythosComposition: [
					{ stage: 1, color: "green", count: 1 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 1 },
					{ stage: 2, color: "green", count: 3 },
					{ stage: 2, color: "yellow", count: 2 },
					{ stage: 2, color: "blue", count: 1 },
					{ stage: 3, color: "green", count: 2 },
					{ stage: 3, color: "yellow", count: 4 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
			{
				id: 10,
				name: "Nephren-Ka",
				mythosComposition: [
					{ stage: 1, color: "green", count: 0 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 2 },
					{ stage: 2, color: "green", count: 1 },
					{ stage: 2, color: "yellow", count: 3 },
					{ stage: 2, color: "blue", count: 0 },
					{ stage: 3, color: "green", count: 3 },
					{ stage: 3, color: "yellow", count: 4 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
		],
	},
	{
		expansionID: 5,
		cards: [
			{
				id: 11,
				name: "Hastur",
				mythosComposition: [
					{ stage: 1, color: "green", count: 0 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 2 },
					{ stage: 2, color: "green", count: 2 },
					{ stage: 2, color: "yellow", count: 3 },
					{ stage: 2, color: "blue", count: 0 },
					{ stage: 3, color: "green", count: 3 },
					{ stage: 3, color: "yellow", count: 5 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
		],
	},
	{
		expansionID: 6,
		cards: [
			{
				id: 12,
				name: "Atlach-Nacha",
				mythosComposition: [
					{ stage: 1, color: "green", count: 1 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 1 },
					{ stage: 2, color: "green", count: 3 },
					{ stage: 2, color: "yellow", count: 2 },
					{ stage: 2, color: "blue", count: 1 },
					{ stage: 3, color: "green", count: 2 },
					{ stage: 3, color: "yellow", count: 4 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
			{
				id: 13,
				name: "Hypnos",
				mythosComposition: [
					{ stage: 1, color: "green", count: 0 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 1 },
					{ stage: 2, color: "green", count: 2 },
					{ stage: 2, color: "yellow", count: 3 },
					{ stage: 2, color: "blue", count: 1 },
					{ stage: 3, color: "green", count: 3 },
					{ stage: 3, color: "yellow", count: 4 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
		],
	},
	{
		expansionID: 7,
		cards: [
			{
				id: 14,
				name: "Shudde M'ell",
				mythosComposition: [
					{ stage: 1, color: "green", count: 0 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 2 },
					{ stage: 2, color: "green", count: 4 },
					{ stage: 2, color: "yellow", count: 2 },
					{ stage: 2, color: "blue", count: 0 },
					{ stage: 3, color: "green", count: 2 },
					{ stage: 3, color: "yellow", count: 4 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
		],
	},
	{
		expansionID: 8,
		cards: [
			{
				id: 15,
				name: "Antediluvium",
				mythosComposition: [
					{ stage: 1, color: "green", count: 1 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 1 },
					{ stage: 2, color: "green", count: 2 },
					{ stage: 2, color: "yellow", count: 3 },
					{ stage: 2, color: "blue", count: 1 },
					{ stage: 3, color: "green", count: 2 },
					{ stage: 3, color: "yellow", count: 4 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
			{
				id: 16,
				name: "Nyarlathotep",
				mythosComposition: [
					{ stage: 1, color: "green", count: 1 },
					{ stage: 1, color: "yellow", count: 2 },
					{ stage: 1, color: "blue", count: 1 },
					{ stage: 2, color: "green", count: 2 },
					{ stage: 2, color: "yellow", count: 3 },
					{ stage: 2, color: "blue", count: 1 },
					{ stage: 3, color: "green", count: 2 },
					{ stage: 3, color: "yellow", count: 4 },
					{ stage: 3, color: "blue", count: 0 },
				],
			},
		],
	},
];
