// List of spaces available for random selection.
// Extend these arrays as needed; names are illustrative and not exhaustive.
const spacesData = {
    base: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "San Francisco",
        "Arkham",
        "The Amazon",
        "Buenos Aires",
        "London",
        "Rome",
        "The Pyramids",
        "The Heart of Africa",
        "Antarctica",
        "Istanbul",
        "Tunguska",
        "The Himalayas",
        "Shanghai",
        "Tokyo",
        "Sydney",
    ],
    Antarctica: [
        "City of the Elder Things",
        "Plateau of Leng",
        "Frozen Waste",
        "Snowy Mountains",
        "Lake Camp",
        "Miskatonic Outpost",
    ],
    Dreamlands: [
        "Unknown Kadath",
        "The Enchanted Wood",
        "Ulthar",
        "Celephais",
        "Dylath-Leen",
        "The Underworld",
        "The Moon",
    ],
    Egypt: [
        "The Sahara Desert",
        "Alexandria",
        "Tel el-Amarna",
        "The Bent Pyramid",
        "Cairo",
        "The Nile River",
    ],
};
